version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: dep12_takas
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dep12_takas
    network_mode: host
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local